"""your message

Revision ID: 376aba6a81fb
Revises: dbe80faf2c6f
Create Date: 2024-01-18 10:04:39.772052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376aba6a81fb'
down_revision = 'dbe80faf2c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
